### ISSUE TITLE
Custom tags produces errors

### ISSUE THREAD

**Issue by pySilver** [davidodenwald/prettier-plugin-jinja-template#16]
Template like this

```jinja
{% extends "base.jinja2" %}

{% block content %}
  {% cachalot get_last_invalidation('catalog.SectionPage', 'core.ReusableContent', 'blogs.BlogPostPage'),
  page.pk, page.content.raw_data, cache_key='catalog_main_section_page_content', timeout=86400 %}
  {{ schema_webpage(page) }}
  {% include_block page.content %}
{% endcachalot %}
{% endblock %}
```

Throws formatting error:

```bash
mybaze/templates/search_terms/search_term_page.jinja2
[error] mybaze/templates/search_terms/search_term_page.jinja2: Error: Closing statement "endcachalot" doesn't match Opening Statement "include_block page.content".
[error]     at Object.parse (/Users/Silver/Projects/mybaze/node_modules/prettier-plugin-jinja-template/lib/parser.js:112:31)
[error]     at parse (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:17080:24)
[error]     at async coreFormat (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18401:7)
[error]     at async formatWithCursor (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18603:14)
[error]     at async formatFiles (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6778:18)
[error]     at async main (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6970:5)
[error]     at async Module.run (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6924:5)
```

**Comment by pySilver** [comment]
Also it goes crazy when tags that does not need a closing pair are used:

```
mybaze/templates/home/home_page.jinja2
[error] mybaze/templates/home/home_page.jinja2: Error: Closing statement "endcachalot" doesn't match Opening Statement "include_block page.content".
[error]     at Object.parse (/Users/Silver/Projects/mybaze/node_modules/prettier-plugin-jinja-template/lib/parser.js:112:31)
[error]     at parse (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:17080:24)
[error]     at async coreFormat (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18401:7)
[error]     at async formatWithCursor (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18603:14)
[error]     at async formatFiles (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6778:18)
[error]     at async main (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6970:5)
[error]     at async Module.run (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6924:5)
```

```
[error] mybaze/templates/menus/menu_detail_mobile.jinja2: Error: Closing statement "endif" doesn't match Opening Statement "trans "Close menu"".
[error]     at Object.parse (/Users/Silver/Projects/mybaze/node_modules/prettier-plugin-jinja-template/lib/parser.js:112:31)
[error]     at parse (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:17080:24)
[error]     at async coreFormat (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18401:7)
[error]     at async formatWithCursor (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/index.mjs:18603:14)
[error]     at async formatFiles (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6778:18)
[error]     at async main (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6970:5)
[error]     at async Module.run (file:///opt/homebrew/Cellar/prettier/3.0.0/libexec/lib/node_modules/prettier/internal/cli.mjs:6924:5)
```

**Comment by davidodenwald** [comment]
I reworked the statement logic to allow custom non-closing statements.
Your code should work now with the latest release 1.2.0.
